# Rustfmt configuration for Miller
# https://rust-lang.github.io/rustfmt/

edition = "2021"

# Formatting options
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"

# Imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Functions
fn_single_line = false
where_single_line = false

# Structs and enums
struct_lit_single_line = false
enum_discrim_align_threshold = 0

# Comments
normalize_comments = true
wrap_comments = true
comment_width = 100

# Control flow
control_brace_style = "AlwaysSameLine"

# Misc
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
